<a href="https://colab.research.google.com/github/ncarolan/COS302/blob/main/HW2/HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# COS 302 - HW2

In [1]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

## Problem 2

### (A)

In [2]:
foo = np.arange(30)
print(f'{foo} with shape: {foo.shape}')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] with shape: (30,)


### (B)

In [3]:
bar = foo.reshape((2,15))
print(f'{bar} with shape: {bar.shape}')

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] with shape: (2, 15)


### (C)

In [4]:
baz = foo.reshape((2,3,5))
print(f'{baz} with shape: {baz.shape}')

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]] with shape: (2, 3, 5)


### (D)

In [5]:
bar[1, 0] = -1
print(f'bar:\n {bar}')

print(f'foo:\n {foo}')
print(f'baz:\n {baz}')

bar:
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [-1 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
foo:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 -1 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
baz:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[-1 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Numpy [`reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) typically returns a view object, which references the data of the original array in memory, rather than creating a new copy with the new dimensions. Because of this, changing the values in a reshaped view also changes those values in the original array and other views.

### (E)

In [6]:
# (i) Sum baz over its second dimension and print the result.
res = baz.sum(axis=1)
print(f'{res} with shape {res.shape}')

[[15 18 21 24 27]
 [44 63 66 69 72]] with shape (2, 5)


In [7]:
# (ii) Sum baz over its third dimension and print the result.
res = baz.sum(axis=2)
print(f'{res} with shape {res.shape}')

[[ 10  35  60]
 [ 69 110 135]] with shape (2, 3)


In [8]:
# (iii) Sum baz over both its first and third dimensions and print the result.
res = baz.sum(axis=(0,2))
print(f'{res} with shape {res.shape}')

[ 79 145 195] with shape (3,)


### (F)

In [9]:
# (i) Slice out the second row of bar and print it.
res = bar[1, :]
print(f'{res} with shape {res.shape}')

[-1 16 17 18 19 20 21 22 23 24 25 26 27 28 29] with shape (15,)


In [10]:
# (ii) Slice out the last column of bar using the -1 notation and print it.
res = bar[:, -1]
print(f'{res} with shape {res.shape}')

[14 29] with shape (2,)


In [11]:
# (iii) Slice out the top right 2 × 2 submatrix of bar and print it.
res = bar[:2, -2:]
print(f'{res} with shape {res.shape}')

[[13 14]
 [28 29]] with shape (2, 2)


## Problem 3

### (A)

In [12]:
vals = np.arange(10) + 1
print(f'{vals} with shape {vals.shape}')

[ 1  2  3  4  5  6  7  8  9 10] with shape (10,)


### (B)

In [13]:
res = vals.reshape((10,1))
res = res + vals
print(f'{res} with shape {res.shape}')

[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]] with shape (10, 10)


### (C)

In [14]:
import numpy.random as npr
data = np.exp(npr.randn(50,5))

print(f'{data} with shape {data.shape}')

[[ 3.198  0.484  0.779  0.133  2.481]
 [ 5.794  5.368  0.522  5.717  1.297]
 [ 2.14   0.234  1.799  2.274  1.553]
 [ 0.36   1.115  2.358  3.856  0.426]
 [ 1.202  2.054  0.64   0.592  1.263]
 [ 2.12   5.397  0.529  0.224  1.56 ]
 [ 1.036  0.346  1.08   5.051  2.558]
 [ 0.421  2.806  0.077  0.961  0.831]
 [ 1.987  0.831  0.549  0.826  0.367]
 [ 0.192  0.872  0.466  3.893  8.021]
 [ 0.932  1.37   1.378  2.671  1.149]
 [ 2.325  1.947  1.603  2.417  0.689]
 [ 0.382  0.287  2.783  1.612  1.067]
 [ 1.614  0.54   0.816  0.32   0.295]
 [ 2.524  0.985  1.958  0.426  0.333]
 [ 0.595  1.141  1.026  0.649  3.147]
 [ 0.742  0.196  0.221  2.214  0.402]
 [ 1.23   2.395  2.117  7.713  0.491]
 [ 2.141  2.669  4.436  0.77   3.505]
 [ 2.32   2.675  6.029  1.674  0.841]
 [ 0.823  0.75   0.745  6.095  0.505]
 [ 0.524  0.743  2.253  9.85   0.124]
 [ 0.294  1.288  0.294  1.524  1.732]
 [ 0.265  1.123  2.366  0.896 13.608]
 [ 0.139  0.274  0.817  0.332  1.883]
 [ 1.366  2.16   4.234  0.816  0.984]
 [ 2.876  0.

### (D)

In [15]:
means = data.mean(axis=0)
stds = data.std(axis=0)

print(f'means: {means}')
print(f'stds: {stds}')

means: [1.386 1.476 1.544 2.844 2.007]
stds: [1.268 1.716 1.33  6.576 2.215]


### (E)

In [16]:
normalized = (data - means) / stds
print(f'{normalized} with shape {normalized.shape}')

print(f'means: {normalized.mean(axis=0)}')
print(f'stds: {normalized.std(axis=0)}')

[[ 1.429 -0.579 -0.576 -0.412  0.214]
 [ 3.477  2.268 -0.769  0.437 -0.321]
 [ 0.595 -0.724  0.191 -0.087 -0.205]
 [-0.809 -0.21   0.612  0.154 -0.714]
 [-0.145  0.337 -0.68  -0.342 -0.336]
 [ 0.579  2.285 -0.763 -0.398 -0.202]
 [-0.276 -0.659 -0.349  0.336  0.249]
 [-0.761  0.775 -1.104 -0.286 -0.531]
 [ 0.474 -0.376 -0.748 -0.307 -0.74 ]
 [-0.942 -0.352 -0.811  0.16   2.714]
 [-0.358 -0.062 -0.125 -0.026 -0.387]
 [ 0.741  0.274  0.044 -0.065 -0.595]
 [-0.792 -0.693  0.932 -0.187 -0.424]
 [ 0.18  -0.546 -0.547 -0.384 -0.773]
 [ 0.898 -0.286  0.311 -0.368 -0.756]
 [-0.623 -0.195 -0.39  -0.334  0.515]
 [-0.508 -0.746 -0.995 -0.096 -0.725]
 [-0.123  0.535  0.43   0.74  -0.684]
 [ 0.595  0.695  2.175 -0.315  0.676]
 [ 0.737  0.698  3.373 -0.178 -0.526]
 [-0.444 -0.423 -0.601  0.494 -0.678]
 [-0.68  -0.428  0.533  1.065 -0.85 ]
 [-0.861 -0.11  -0.94  -0.201 -0.124]
 [-0.884 -0.206  0.618 -0.296  5.236]
 [-0.983 -0.701 -0.547 -0.382 -0.056]
 [-0.015  0.399  2.023 -0.308 -0.462]
 [ 1.175 -0.

## Problem 4

### (A)

In [17]:
def vandermonde(N):
  """For a natural number N, returns a Vandermonde matrix for a vector [1,2,...,N]^T."""
  vec = np.arange(N) + 1
  vec = vec.reshape((N,1))
  return vec ** np.arange(N)

In [18]:
vander = vandermonde(12)
print(f'{vander} with shape {vander.shape}')

[[           1            1            1            1            1
             1            1            1            1            1
             1            1]
 [           1            2            4            8           16
            32           64          128          256          512
          1024         2048]
 [           1            3            9           27           81
           243          729         2187         6561        19683
         59049       177147]
 [           1            4           16           64          256
          1024         4096        16384        65536       262144
       1048576      4194304]
 [           1            5           25          125          625
          3125        15625        78125       390625      1953125
       9765625     48828125]
 [           1            6           36          216         1296
          7776        46656       279936      1679616     10077696
      60466176    362797056]
 [           1        

### (B)

In [19]:
x = np.ones(12)

b = vander @ x
print(f'b={b}')

b=[1.200e+01 4.095e+03 2.657e+05 5.592e+06 6.104e+07 4.354e+08 2.307e+09
 9.817e+09 3.530e+10 1.111e+11 3.138e+11 8.106e+11]


### (C)

In [20]:
res = np.linalg.inv(vander) @ b.T
print(f'x={res}')

x=[-12.27    5.906  15.422  -6.035   2.059   0.927   1.002   1.      1.
   1.      1.      1.   ]


We expect the values in x to be 1, or aproximately 1. We set up `Vx=b` with `x` being a vector of ones, and `V` computed above. From this we find the values of `b` by taking the product. Now given `b` and `V`, we can compute `x` as `x=V^-1 b`. However, we find that the resulting `b` vectors differs significantly from the true value due to numerical problems with matrix inversion on computers.

### (D)

In [21]:
res = np.linalg.solve(vander, b)
print(f'x={res}')

x=[0.981 1.051 0.945 1.032 0.989 1.002 1.    1.    1.    1.    1.    1.   ]


These results are much closer to the true values of 1.